name: Build and Push Experimental PipeWire Image

on:
  workflow_dispatch:
  push:
    branches:
      - native-pipewire-test

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: luciobt/owntone-pulseaudio:dev
          build-args: |
            REPOSITORY_URL=https://github.com/Topolynx/owntone-server.git
            REPOSITORY_BRANCH=pipewire-native
            REPOSITORY_COMMIT=e3355d91d8da8c05cc04a59b44efc6792dd28582
          cache-from: type=gha,scope=pipewire-dev
          cache-to: type=gha,mode=max,scope=pipewire-dev
